# Generated by Django 6.0.3 on 2026-04-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image2',
            field=models.ImageField(null=True, upload_to='images2'),
        ),
    ]
