# Generated by Django 6.0.4 on 2026-05-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_student_profile_pic_teacher_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='profile_pic',
        ),
    ]
