# Generated by Django 6.0.4 on 2026-05-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_student_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accent_color',
            field=models.CharField(default='#4f46e5', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='announcement_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='attendance_reports',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='exam_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='accent_color',
            field=models.CharField(default='#4f46e5', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='announcement_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='attendance_reports',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='exam_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
