# Generated by Django 6.0.4 on 2026-04-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='availability',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
