# Generated by Django 6.0.3 on 2026-03-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('pid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=20)),
                ('pdesc', models.CharField(max_length=100)),
                ('pdate', models.DateField()),
            ],
        ),
    ]
